% Compute scalogram

% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 06-Feb-2020 15:40:35

% Parameters
timeLimits = [0 30]; % seconds
frequencyLimits = [0 50]; % Hz
voicesPerOctave = 16;
timeBandWidth = 10;

%%
% Index into signal time region of interest
v2_2_ROI = v2(:,2);
sampleRate = 100; % Hz
startTime = 0; % seconds
timeValues = startTime + (0:length(v2_2_ROI)-1).'/sampleRate;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits




(2);
v2_2_ROI = v2_2_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);



%%
% Limit the cwt frequency limits
frequencyLimits(1) = max(frequencyLimits(1),...
    cwtfreqbounds(numel(v2_2_ROI),sampleRate,...
    'TimeBandWidth',timeBandWidth));

% Compute cwt
% Run the function call below without output arguments to plot the results
[WT,F] = cwt(v2_2_ROI,sampleRate, ...
    'VoicesPerOctave',voicesPerOctave, ...
    'TimeBandWidth',timeBandWidth, ...
    'FrequencyLimits',frequencyLimits);
